### ISSUE TITLE
Edit bot not working

### ISSUE THREAD

**Issue by leandroneves** [Ilhasoft/bothub#1]
**Description:**  
Edit bot not working 

> **Browser:** Edge 
> **OS:** Windows 10  
> **Authenticated**: No  

I can not edit the information for a bot.
Clicking on edit button in the created bot will loop load.

**Steps to reproduce the error:**

1. Enter in your bot 
2. Click on edit button

**Comment by douglasppaz** [comment]
@leandroneves try edit bot now..
