### ISSUE TITLE
Improvement on UX

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub#10]
**Description:**  
 
- Add a placeholder to the textfield where the user should type a new phrase;
- Force lowercased letter on the intent textfield;
- Disable "Submit example" button while there is any missing field;

> **Browser:** Any
> **OS:** Any
> **Authenticated**: Yes  
> **URL**: Any bot

**Steps to reproduce the error:**

1. Type a new intent title;
2. Keep the phrase field blank;
3. Try to submit a new example;

The user receives a error, these errors could be simplified if the submit button become disabled.

**Comment by douglasppaz** [comment]
Enhancements implemented [here](https://github.com/Ilhasoft/bothub-webapp/pull/161).
