### ISSUE TITLE
 Broken image links

### ISSUE THREAD

**Issue by johncordeiro** [Ilhasoft/bothub#109]
[![Screenshot_2019-09-24_12-27-24.png](https://mrkr.io/s/5d8a0bacf5690c598424f3bb/2)](https://mrkr.io/s/5d8a0bacf5690c598424f3bb/0)

"Invitation" and "Request Approved" emails aren't displaying the images correctly.

---
### More Info

**Reported by:** Tales Souza (tales@ilhasoft.com.br)
**Source URL**: [https://mail.google.com/mail/u/0/#label/Push/FMfcgxwDrRRZKsvZgDFBLqzLKXwttSGf](https://mail.google.com/mail/u/0/#label/Push/FMfcgxwDrRRZKsvZgDFBLqzLKXwttSGf)

<table><tr><td><strong>Browser</strong></td><td>Chrome 77.0.3865.75</td></tr><tr><td><strong>Screen Size</strong></td><td>1360 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 738</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by dyohan9** [comment]
Problem solved and applied in production.
