### ISSUE TITLE
Bug - Deletion Training

### ISSUE THREAD

**Issue by IlhasoftPeter** [Ilhasoft/bothub#14]
**Bug - Deletion Training:**  
Deleted examples are persisting in training, and this factor is cumulative if you continue testing on **Analyze Text**.

> **Browser:** Google Chrome  
> **OS:** Ubuntu 17.10
> **Authenticated**: Yes  
> **URL**: https://bothub.it/Peter/susana_mkt/  

Deleting examples in the Bothub repository, the intent decision confidence persists and accumulates if I repeat the process, increasing the result.

**Steps to reproduce the error:**

1. Enter the example "Eu quero fazer uma simulação" and click the **Train** button;
2. Go to **Analyze text**, enter the same example and click the **Analyze** button;
       The confidence will return a wrong intention decision:
                Intention: "contato";
                (N)% confidence.
3. Delete the repository example by clicking the trash icon;
4. Repeat step 2 and you will see that the confidence is greater than the previous one.

**Comment by douglasppaz** [comment]
Fixed in NLP repository...
