### ISSUE TITLE
Simulator isn't working well for labels detection

### ISSUE THREAD

**Issue by johncordeiro** [Ilhasoft/bothub#19]
**Description:**  
You have trained many sentences with labels, and now you want to test by using the simulator. It's not showing up the predictions.

> **Browser:** Chrome  
> **OS:** OSX  
> **Authenticated**: Yes
> **URL**: https://localhost/

**Comment by douglasppaz** [comment]
Resolved at https://github.com/Ilhasoft/bothub-webapp/commit/f718144e9a238ac55abf6e97438bd8a981e24221
