### ISSUE TITLE
Ghost Intent

### ISSUE THREAD

**Issue by IlhasoftPeter** [Ilhasoft/bothub#26]
Intents that have been deleted continue appearing in autocomplete and status!
 
> **URL**: https://bothub.it/Peter/susana_mkt/

If you train a new intent and delete it later, that intent will continue to exist in the autocomplete and Status of your bot repository!

**Steps to reproduce the error:**

1. Train a new Intent;
2. Delete it after;
3. Check in Status. You will see the GHOST INTENT.

**Comment by douglasppaz** [comment]
Will be fixed at the next deploy
