### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub#29]
**Description:**  
After uploading new examples to my repository I just tried to train it, but I got an 500 internal server error many times.

> **Browser:** Chrome  
> **OS:** Any
> **Authenticated**: Yes
> **URL**: https://bothub.it/pericles/whoareyou/

Is that a serious issue? Cause it already happened with me a few times, I don't know why this is happening, and how to solve this neither. Please fix this, looks like the system isn't stable.

**Comment by douglasppaz** [comment]
@periclesJ the problem persists?

**Comment by periclesJ** [comment]
@douglasppaz I've never seen this anymore
