### ISSUE TITLE
Automatic training in browser Edge

### ISSUE THREAD

**Issue by leandroneves** [Ilhasoft/bothub#3]
**Description:**  
In the Edge browser, when you assign an entity and click the OK button, the Submit Example action is executed.

> **Browser:** Edge
> **OS:** Windows 10 
> **Authenticated**: Yes 
> **URL**: https://bothub.it  

**Steps to reproduce the error:**

1. In the navigated Edger, enter a bot.
2. Go to the Examples tab
3. Write a sentence and select a word
4. Add the name to an entity and click ok

**Comment by douglasppaz** [comment]
We are working on a solution [here](https://github.com/Ilhasoft/bothub-webapp/pull/161).
