### ISSUE TITLE
Edit repository slug

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub#34]
**Description:**  
When you have to edit your repository configs, and changes its slug, after saving the changes the screen reloads with the old slug and says that the repository doesn't exist. it's a weird behaviour.

> **Browser:** Any  
> **OS:** Any
> **Authenticated**: Yes  
> **URL**: Any of your repositories

**Steps to reproduce the error:**

1. Open up one of your repositories.
2. Tap edit button to start editing your repository.
3. Change the repository slug and try to save it.

The bothub presents an error that looks like your repository doesn't exist anymore.

**Comment by douglasppaz** [comment]
Issue solved in bothub-webapp version 2.
I close this issue, after new version deployment I send new message here.
