### ISSUE TITLE
Very abrupt transition between tabs

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#37]
**Description:**  
The loading when switching between tabs on bot's screen is too abrupt.

> **Browser:** any
> **OS:** any
> **Authenticated**: No  
> **URL**: https://bothub.it/johncordeiro/testing_again 

![loading](https://user-images.githubusercontent.com/39275274/47442196-523c2e80-d788-11e8-87ae-73d2255a06e6.gif)

Is it really necessary to reload the entire page? Is it possible to reload only the inside of the tab?

**Steps to reproduce the error:**

1. Click on any bot in bot's listing
2. Switch between tabs.

**Comment by douglasppaz** [comment]
@tainailhasoft this is the next step of your roadmap. When V2 be finished, we be start work in a cache system to solve this problems.
