### ISSUE TITLE
Low contrast on tags

### ISSUE THREAD

**Issue by tainailhasoft** [Ilhasoft/bothub#39]
**Description:**  
In my screen, the tag's background is almost invisible.

> **Browser:** any  
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/johncordeiro/testing_again

![image](https://user-images.githubusercontent.com/39275274/47443790-7e0ce380-d78b-11e8-9919-5bd81d36bf6b.png)

**Steps to reproduce the error:**

1. Just take a look on the tags

**Comment by douglasppaz** [comment]
We need define a color palette and color rules. I created this issue https://github.com/Ilhasoft/bothub-webapp/issues/250 to create docs.
