### ISSUE TITLE
Intent field not formatted in browser edge

### ISSUE THREAD

**Issue by leandroneves** [Ilhasoft/bothub#4]
**Description:**  
The Intent field not formatted in browser edge.

> **Browser:** Edge
> **OS:** Windows 10  
> **Authenticated**: Yes  
> **URL**: https://bothub.it.  

**Steps to reproduce the error:**

1. In the navigated Edger, enter a bot.
2. Go to the Examples tab
3. You will see the Unformatted Intent field

![image](https://user-images.githubusercontent.com/1843614/41097368-0ca582bc-6a2e-11e8-83ff-8acb177597d7.png)

**Comment by douglasppaz** [comment]
Maybe adding Cleave.js would be a great solution for it, there is an issue [opened in webapp](https://github.com/Ilhasoft/bothub-webapp/issues/144) about it.
