### ISSUE TITLE
Bots aren't loading when logged

### ISSUE THREAD

**Issue by tainailhasoft** [Ilhasoft/bothub#41]
**Description:**  
Bot details screen is not loading when I'm logged, not even if the bot is mine.

> **Browser:** Mozilla Firefox  
> **OS:** any 
> **Authenticated**: Yes
> **URL**: https://bothub.it/

**Steps to reproduce the error:**

1. Log in
2. Click on any bot

**Comment by douglasppaz** [comment]
I could not reproduce this error here, I tested in production and staging environment.

**Comment by tainailhasoft** [comment]
I think it was a network problem, sorry!
