### ISSUE TITLE
General adjustments on Trainings screen

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#53]
**Description:**  

![image](https://user-images.githubusercontent.com/39275274/47667445-c0b42e80-db84-11e8-9751-d70f1fce5bcf.png)

- Improve navigation breadcrumbs and icon
- Improve **Intents**/**Labels** listing
- Ajustments on textarea/dropdown labels

> **Browser:** any
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/ any bot training screen

**Comment by johncordeiro** [comment]
This was converted to task and designed by the UI/UX team (powered by @tainarte)
