### ISSUE TITLE
 General adjustments on Settings screen

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#56]
**Description:**  

- Adjust paddings and size of the form elements
- Review all text and labels of this page
- Make a better arrangement of the sections

> **Browser:** any
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/ any bot settings screen

**Comment by tainarte** [comment]
![captura de tela 2018-11-05 as 16 26 54](https://user-images.githubusercontent.com/39275274/48021716-08543080-e118-11e8-8b78-e75db45f03dd.png)
![captura de tela 2018-11-05 as 16 27 05](https://user-images.githubusercontent.com/39275274/48021719-09855d80-e118-11e8-9f1b-6969d05bf2ba.png)

**Comment by johncordeiro** [comment]
This was converted to task and designed by the UI/UX team (powered by @tainarte)
