### ISSUE TITLE
Move "Updates" to Status tab

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#58]
**Description:**  

I know that maybe it's not possible to do right now, but the **Updates** section is inside **Analyze Text** tab and it makes no sense, I think it should be on **Status** tab (especially if we change it's name to **Summary**)

![image](https://user-images.githubusercontent.com/39275274/47673923-c154c100-db94-11e8-92b5-f4c19928915e.png)

> **Browser:** any
> **OS:** any  
> **Authenticated**: any
> **URL**: https://bothub.it/

**Comment by johncordeiro** [comment]
This was converted to task and designed by the UI/UX team (powered by @tainarte)
