### ISSUE TITLE
General adjustments on Translated Sentences screen

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#59]
**Description:**  

- [x] Improve contrast
- [x] Include headers for sections (like **Progress** and **History**)
- [x] In history, show clearly the translation that was made without the button to change between original and translation

![image](https://user-images.githubusercontent.com/39275274/47674379-e85fc280-db95-11e8-8e1d-08bf5ed6e930.png)

> **Browser:** any
> **OS:** any
> **Authenticated**: any  
> **URL**: https://bothub.it/

**Comment by tainarte** [comment]
> In history, show clearly the translation that was made without the button to change between original and translation

When I opened another bot, I noticed that this listing shows the intents and more info, so it makes sense to have the **Show original** button. Let's keep it that way in this version.

**Comment by johncordeiro** [comment]
This was converted to task and designed by the UI/UX team (powered by @tainarte)
