### ISSUE TITLE
General adjustments on Status screen

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#60]
**Description:**  

![image](https://user-images.githubusercontent.com/39275274/47674733-c3b81a80-db96-11e8-9ece-94aafc0ebc45.png)

- This screen needs to be rearranged to be more attractive
- Maybe the Updates section should be on this screen too (see #58 )

> **Browser:** any
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/

**Comment by johncordeiro** [comment]
@tainarte what kind of arrangement needs to be done in this case? (besides adding the Updates tab)

**Comment by johncordeiro** [comment]
This was converted to task and designed by the UI/UX team (powered by @tainarte)
