### ISSUE TITLE
Blocked feature message

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub#7]
**Description:**  
Short and descriptive example bug report title

> **Browser:** Chrome  
> **OS:** MacOS
> **Authenticated**: No  
> **URL**: http://bothub.it/

**Steps to reproduce the error:**

1. Try to upvote/downvote any bot.
2. You will receive a message "Authentication credentials were not provided."

This message could be improved, maybe a friendly message asking to the user to log in before up/down voting any bot.

**Comment by tainailhasoft** [comment]
Message suggestion: ”**You must be logged in to perform this action.**”

**Comment by johncordeiro** [comment]
Fixed.
