### ISSUE TITLE
It's possible to train equals phrases as examples

### ISSUE THREAD

**Issue by WilliamTales** [Ilhasoft/bothub#73]
**Description:**  
Even if the phrase is exactly the same, it's allowed to train.

> **Browser:** Chrome  
> **OS:** Linux (Ubuntu 16.04)  
> **Authenticated**: Yes  
> **URL**: http://staging.bothub.it/Captain/action-detection/training  

**Steps to reproduce the error:**

1. Just copy/paste the same phrase and keep adding it as new examples.

**Comment by douglasppaz** [comment]
@WilliamTales this is not a bug or error. You can create another issue to suggest an improvement.

**Comment by johncordeiro** [comment]
Reopening issue as enchancement
