### ISSUE TITLE
Change some categories names

### ISSUE THREAD

**Issue by tainarte** [Ilhasoft/bothub#83]
**Description:**  
Category names are not abbreviated, these two are out of the standard.

![captura de tela 2019-01-02 as 17 13 11](https://user-images.githubusercontent.com/39275274/50610445-c5ad9b00-0eb1-11e9-8f84-e64f993a61db.png)

Tip: Change them to **Technology** and **Configuration**

> **Browser:** any  
> **OS:** any
> **Authenticated**: any
> **URL**: https://bothub.it/...

**Comment by johncordeiro** [comment]
Fixed.
