### ISSUE TITLE
No feedback when trying to create a uppercased/white spaced intents

### ISSUE THREAD

**Issue by periclesJ** [Ilhasoft/bothub#9]
**Description:**  
The user don't receives any feedback from the server telling that he can't create intents with uppercase letters or white spaces.

> **Browser:** Chrome
> **OS:** MacOS
> **Authenticated**: Yes  
> **URL**: Any bot

**Steps to reproduce the error:**

1. Type a new intent with any uppercased letter;
2. Type a new phrase;
3. Try to submit the new example;

**Comment by douglasppaz** [comment]
Fixed in [bothub-webapp](https://github.com/Ilhasoft/bothub-webapp)'s next version
